---
- name: Understanding Vars
  hosts: all
  become: yes
  vars: 
    USRNM: playuser
    COMM: Variable From Playbook
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{USRNM}}"
        comment: "{{COMM}}" 
