---
- name: webserver Setup
  hosts: webserver
  become: yes
  tasks:
    - name: Install Httpd
      ansible.builtin.yum:
        name: httpd
        state: present
    - name: State Service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
    - name: Copy Index File
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
