---
- name: Print Facts
  hosts: all
  tasks:
    - name: Print OS Name
      debug:
        var: ansible_distribution
    - name: Print RAM Memory
      debug:
        var: ansible_memory_mb.real.free
