---
- name: DBserver Setup
  hosts: db01
  become: yes
  tasks:
    - name: Install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present
    - name: Install PyMySql
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present
    - name: Start Mariadb Service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
    - name: Create A New Database 
      mysql_db:
        name: accounts
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

